### ISSUE TITLE
Shimmer not working on Android

### ISSUE THREAD

**Issue by jdrorrer** [oblador/react-native-shimmer#17]
It works as expected on iOS, but not at all on android. I've tested it on android 8.1 with a Pixel device and also version 9 with a Pixel 2 simulator - neither shimmers.

**Comment by jdrorrer** [comment]
Actually, I think it might be related to this issue: https://github.com/oblador/react-native-shimmer/issues/1

Here's the current setup that's working in iOS but not android:
```js
<View style={styles.global.flex}>
          <View
            style={style.textContainer}
          >
            <View style={style.titleTextContainer} width={width}>
              <Shimmer>
                <Text
                  style={style.text}
                />
              </Shimmer>
            </View>

            <View width={subTitleWidth}>
              <Shimmer>
                {subTitle ? <Text style={style.subText} /> : null}
              </Shimmer>
            </View>
          </View>
        </View>
```

**Comment by angelos3lex** [comment]
@jdrorrer Have you found solution for android ? this even doesn't work:
```
 <Shimmer>
   <Text>bla bla.... </Text>
</Shimmer>
```

**Comment by jdrorrer** [comment]
@angelos3lex unfortunately, no I didn't find a solution. We ended up just settling for the fact that it shimmers on iOS and not Android.

**Comment by aditi1126** [comment]
Upgrade build.gradle. Otherwise, use their older version that is, 0.3.2

**Comment by jsastriques** [comment]
Invariant Violation: requireNativeComponent: "RNShimmeringView" was not found in the UIManager.
I have this issue, some help please. Thanks in advance

**Comment by rommyarb** [comment]
I found the solution:

Add **prop-types** to dependency
npm i --save prop-types

and revert back to version **0.4.1**
npm i --save react-native-shimmer@0.4.1

Now it works.

**Comment by rommyarb** [comment]
I found the solution:

Add **prop-types** to dependency
`npm i --save prop-types`

and revert back to version **0.4.1**
`npm i --save react-native-shimmer@0.4.1`

Now it works.

**Comment by aditi1126** [comment]
Even having prop-types won't make it work. Android issue still prevails.

**Comment by rommyarb** [comment]
@aditi1126 have you tried revert back to version 0.4.1 ?

**Comment by sagargulati** [comment]
Any luck so far?

**Comment by lgngnr** [comment]
i make it working in this way:

- Create a new project with expo init
- Run expo eject and choose expoKit so can i have both react-native and expo api
- Run it with expo start
- Install npm i --save react-native-shimmer
- Link dependencies react-native link react-native-shimmer
- Meanwhile expo start still running open the android project with android studio and run it or just from command line cd android and ./gradlew installDevKernelDebug, it'll build the apk, install and run it on the device/emulator connected through adb. If doesn't run automatically just open app drawer and open the installed apk

**Comment by sagargulati** [comment]
Avoiding playing with Expo, Any direct package issue you found?

**Comment by jdrorrer** [comment]
@rommyarb strange, it does work when switching to version 0.4.1! 🤷‍♂️

**Comment by sagargulati** [comment]
@jdrorrer @rommyarb : It only making the text SHIMMER. I'm looking for more of a placeholder where it shows loading shimmer for images and text (like facebook)
Any example for that?

**Comment by alittletf** [comment]
@jdrorrer So it works for you in the above implementation on 0.4.1? I installed that version and can't seem to get it to work on Android...works fine on iOS. Do you use the prop-types package in conjunction with react-native-shimmer? If so, how are you using that?

**Comment by jdrorrer** [comment]
@alittletf It works for me with 0.4.1 - I also have a Pixel 3 running Android 9. I am using prop-types as well - not sure how/why that would affect this library, though. Here's an example skeleton loading item I'm using for reference so you can see how I'm using Shimmer and prop-types:

`import React, { PureComponent } from 'react';
import { Image, StyleSheet, View } from 'react-native';
import { Icon } from 'react-native-elements';
import Shimmer from 'react-native-shimmer';
import Card from 'components/theme/card';
import PropTypes from 'prop-types';
import styles from '../styles';

const { gray } = styles.vars;

const style = StyleSheet.create({
  avatar: {
    backgroundColor: gray,
    borderRadius: 44 / 2,
    height: 44,
    opacity: 0.45,
    width: 44
  },
  badge: {
    backgroundColor: gray,
    borderRadius: 20 / 2,
    height: 20,
    opacity: 0.45,
    position: 'absolute',
    right: -5,
    top: 0,
    width: 20
  },
  cardContainer: {
    ...styles.spacing.padVert12,
    ...styles.spacing.padHoriz16,
    height: 72
  },
  height11: {
    borderRadius: 11 / 2,
    height: 11
  },
  height14: {
    borderRadius: 14 / 2,
    height: 14
  },
  height16: {
    borderRadius: 16 / 2,
    height: 16
  },
  rightIcon: {
    alignSelf: 'center',
    opacity: 0.45
  },
  text: {
    backgroundColor: gray,
    opacity: 0.45
  }
});

export default class SkeletonConversationListItem extends PureComponent {
  static defaultProps = {
    copyWidth: '100%',
    width: '75%',
    subtitleWidth: '55%',
    hasBadge: false,
    rightIcon: '',
    size: 'small'
  };

  static propTypes = {
    copyWidth: PropTypes.string,
    width: PropTypes.string,
    subtitleWidth: PropTypes.string,
    hasBadge: PropTypes.bool,
    rightIcon: PropTypes.string,
    size: PropTypes.oneOf(['small', 'large'])
  };

  render() {
    const {
      copyWidth,
      hasBadge,
      rightIcon,
      width,
      subtitleWidth,
      size
    } = this.props;

    return (
      <Card containerStyle={size === 'small' ? style.cardContainer : ''}>
        <View style={styles.global.rowStartContainerWrap}>
          <View style={[styles.global.flex1]}>
            <View style={style.avatar}>
              <Shimmer>
                <Image style={style.avatar} />
              </Shimmer>
            </View>
          </View>
          <View style={[styles.global.flex4, styles.global.flexColumn]}>
            <View style={[styles.spacing.marginBottom4, styles.global.flexRow]}>
              <View width={width}>
                <Shimmer>
                  <Image style={[style.text, style.height16]} />
                </Shimmer>
              </View>
              <View>
                {hasBadge && (
                  <Shimmer>
                    <Image style={style.badge} />
                  </Shimmer>
                )}
              </View>
            </View>
            <View style={styles.spacing.marginVert4} width={subtitleWidth}>
              <Shimmer>
                <Image style={[style.height11, style.text]} />
              </Shimmer>
            </View>
            {size === 'large' ? (
              <View
                style={[
                  styles.spacing.marginBottom4,
                  styles.spacing.marginRight24
                ]}
              >
                <View width={copyWidth} style={styles.spacing.marginBottom4}>
                  <Shimmer>
                    <Image style={[style.height14, style.text]} />
                  </Shimmer>
                </View>
                <View width={copyWidth}>
                  <Shimmer>
                    <Image style={[style.height14, style.text]} />
                  </Shimmer>
                </View>
              </View>
            ) : null}
          </View>
          {rightIcon ? (
            <View style={style.rightIcon}>
              <Shimmer>
                <Icon name={rightIcon} color={styles.vars.gray} size={24} />
              </Shimmer>
            </View>
          ) : null}
        </View>
      </Card>
    );
  }
}
`

**Comment by alittletf** [comment]
@jdrorrer thank you so much for the code sample. Yeah I saw another person post something about PropTypes which is why I asked but there doesnt seem to be any interaction between it and Shimmer. Very weird. I still can't get mine to work and Ive reduced everything to a plain Text element, wrapped in Shimmer, which is wrapped in a plain View tag and still nothing. I am on RN 0.58.6. What version are you on?

**Comment by jdrorrer** [comment]
@alittletf I am on RN v0.58.6 as well. If you're giving a Text field some padding and a background color to make it look like a box, I don't think that will work - at least I couldn't get it to work. That's why I'm using Image everywhere in my code sample above. I was able to get Text to shimmer when it just has text in it, though, for some reason.

**Comment by chengsam** [comment]
Update android dependency from `'com.facebook.shimmer:shimmer:0.1.0@aar'` to `'com.facebook.shimmer:shimmer:0.5.0'`, but the native code is refactored so you may have to tweak the code yourself.

**Comment by 0hio-creator** [comment]
@chengsam Any hints on what changes to make to the native code to support. I'm not really familiar with Java

**Comment by quran123** [comment]
now it is not supported at all so there is any substitute for it
