### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by rturk** [oblador/react-native-shimmer#2]
Android Native code is also available on GitHub
https://github.com/facebook/shimmer-android

**Comment by oblador** [comment]
The APIs are quite different, but I'll accept PRs adding Android support.

**Comment by IbrahimAmin** [comment]
I made a library that you can use for android https://www.npmjs.com/package/react-native-android-shimmer

**Comment by IbrahimAmin** [comment]
@rturk Let me know if you need any help

**Comment by oblador** [comment]
@IbrahimAmin Awesome, do you mind if I incorporate your work into this package?

**Comment by Ibrahim-GHub** [comment]
@oblador sure thing go ahead :)

**Comment by joncursi** [comment]
Would love to see these two libraries merge!

**Comment by oblador** [comment]
Android version released in [0.3.0](https://github.com/oblador/react-native-shimmer/releases/tag/v0.3.0)
