### ISSUE TITLE
Invariant Violation: Native Component for "RNShimmeringView" does not exist

### ISSUE THREAD

**Issue by aditi1126** [oblador/react-native-shimmer#20]
Installed the package and linked it both for ios and android. Getting this error.
![screen shot 2019-01-23 at 5 35 33 pm](https://user-images.githubusercontent.com/40567216/51605506-50c00500-1f35-11e9-9ea2-55d60ea562de.png)

**Comment by aditi1126** [comment]
Downgrading the version worked for me.

**Comment by putuyoga** [comment]
Whoever got this error, don't forget to add this to your `Podfile`.
```
  pod 'react-native-shimmer', :path => '../node_modules/react-native-shimmer'
```

**Comment by renishdeveloper** [comment]
> Downgrading the version worked for me.

How to downgrade the package ?
