### ISSUE TITLE
Not working inside Stack Navigator

### ISSUE THREAD

**Issue by iamshadmirza** [oblador/react-native-shimmer#21]
Shimmer is working fine when I'm rendering the page alone but with createStackNavigator, it's not working. 
I'm attaching the screenshots for the two : 
1. When it's working: 

![screenshot_1549103929](https://user-images.githubusercontent.com/22999030/52163221-3f30e700-2705-11e9-8274-e26b4f7604d5.png)

2. When it's not working: 

![screenshot_1549103903](https://user-images.githubusercontent.com/22999030/52163227-4ce66c80-2705-11e9-9999-3823b655157b.png)

I'm using Pixel 2 with API 27, environment : android.

**Comment by rommyarb** [comment]
Can I see your codes and your package.json? Thx.

**Comment by dexMateo** [comment]
Im having this issue as well, any ideas?

**Comment by iamshadmirza** [comment]
@dexMateo I switched to react-native-shimmer-placeholder

**Comment by sagargulati** [comment]
How to make it work like placeholder? Any example code?

**Comment by chengsam** [comment]
Update android dependency from `'com.facebook.shimmer:shimmer:0.1.0@aar'` to `'com.facebook.shimmer:shimmer:0.5.0'`, but the native code is refactored so you may have to tweak the code yourself.

**Comment by oblador** [comment]
Newly released version `0.6.0` is using `com.facebook.shimmer:shimmer:0.5.0`. Closing this issue for now.
