### ISSUE TITLE
Shimmer not working on IOS RN 0.59.1

### ISSUE THREAD

**Issue by mandhu** [oblador/react-native-shimmer#22]
IOS compile error
Xcode v 10.1
error: Build input file cannot be found: '........./RN59/node_modules/react-native-shimmer/ios/Shimmer/FBShimmering/FBShimmeringView.m'
any solution?

**Comment by oferRounds** [comment]
Any solution?

**Comment by emusgrave** [comment]
You are running into an issue with the latest change in 0.5.0 to remove the FBShimmering submodule. Now this project expects you to use Cocoapods.
There is more detail in the PR. I just outlined the problem there: https://github.com/oblador/react-native-shimmer/pull/18#issuecomment-486902678

If anyone has a workaround, I'm all ears. For now though, just downgrade to 0.4.1.

**Comment by lordkiz** [comment]
Using `pod 'react-native-shimmer', :path => '../node_modules/react-native-shimmer'` instead of the documented `pod 'react-native-shimmer', :path => '/node_modules/react-native-shimmer'`  in your podfile allows you to properly install and fixes the error.

**Comment by oblador** [comment]
Using RN 60 or later it should work completely out of the box with auto-linking which is based on CocoaPods.
