### ISSUE TITLE
style issue with text

### ISSUE THREAD

**Issue by samratshekhar** [oblador/react-native-shimmer#3]
Here's my layout:
```javascript
<View style={styles.introTextContainer}>
          <Shimmer
            animating={isLoading}
            animationOpacity={0.2}
          >
            <Text style={[styles.text, styles.introText]}>
              Investing with AI.{'\n'}
              Automated. End to End.
            </Text>
          </Shimmer>
          <Shimmer
            animating={isLoading}
            animationOpacity={0.2}
          >
            <Text style={[styles.text, styles.introSubtext]}>
              Portfolios that invest using Artificial Intelligence, Data Science
              and Machine Learning
            </Text>
          </Shimmer>
</View>
```
& here's the styling:
```javascript
text: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '400',
    margin: 10,
  },
  introTextContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'center',
  },
  introText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '400',
  },
  introSubtext: {
    color: Colors.lightSecondaryText,
  },
```
Seems `<Shimmer>` component somehow screws up the styling of the `<Text>`. If i encapsulate the text component in a `<View>` component, the styling works fine but the shimmering stops as mentioned in #1 

text not centered here:
<img width="374" alt="screen shot 2017-03-22 at 8 06 05 pm" src="https://cloud.githubusercontent.com/assets/25629471/24203192/0bc7d93e-0f3b-11e7-98b9-cfbc4e0ee945.png">

text centered since encapsulated in a view
<img width="376" alt="screen shot 2017-03-22 at 8 05 27 pm" src="https://cloud.githubusercontent.com/assets/25629471/24203211/18d0f53e-0f3b-11e7-9dae-95fdd004df46.png">

**Comment by prithsharma** [comment]
Facing the same.
@oblador any workaround for this you think?

**Comment by samratshekhar** [comment]
fixed it! Replacing the `margin` with `padding` for style `text` did the job. But still leaves the question of why shimmer content is overFlowing if margin is used?
