### ISSUE TITLE
Shimmer color coming in rounded-radius corner while shimmer

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [oblador/react-native-shimmer#44]
<Shimmer style={{flex: 1,alignSelf: "center", height: 56, width: "90%", borderRadius: 10 ,marginBottom: 16, flexDirection: 'row', backgroundColor: 'red'}}>
                <Text style={{ padding: 15, backgroundColor: '#D6D6D6', borderRadius: 10, height: 20}}>rahul pant</Text>
  </Shimmer>

"react-native-shimmer": "^0.6.0",
"react-native" : "0.69.8"
"react" : "18.2.0"

![shimmer](https://github.com/oblador/react-native-shimmer/assets/32297380/a0c5a509-2ccd-4c88-a02d-11c9c1979632)

![shimmer](https://github.com/oblador/react-native-shimmer/assets/32297380/238a0a55-6d6f-4681-b51d-03da021c5243)

how to remove this corner color

**Comment by RahulPant1289** [comment]
Can anyone please help here.

**Comment by CHANDRAMOHANnegi** [comment]
overflow:hidden
