### ISSUE TITLE
React/RCTViewManager.h file not not found

### ISSUE THREAD

**Issue by pyadav** [oblador/react-native-shimmer#6]
According to React-Native release v0.40.0 -
https://github.com/facebook/react-native/releases/tag/v0.40.0

There is a breaking change in iOS native headers import.

> This change affects all native modules and application code on iOS that refer to react native .h files

Please support for below version too 👍

**Comment by oblador** [comment]
Hi, ensure you're on [0.2.1](https://github.com/oblador/react-native-shimmer/releases/tag/v0.2.1)

**Comment by piyush565** [comment]
/Users/../node_modules/react-native-material-kit/iOS/RCTMaterialKit/TickViewManager.m:9:9: 'React/RCTViewManager.h' file not found

can anybody help me with this.? build gets failed in this

**Comment by oblador** [comment]
Why do you think that is related to this module @piyush565? Error says `react-native-material-kit`
