### ISSUE TITLE
Shimmer has no propType

### ISSUE THREAD

**Issue by rubi** [oblador/react-native-shimmer#9]
I come across the problem, like this "Shimmer has no propType for native prop ''RnShimmeringView.onLayout" of native type 'boolean', how to resolve it.

**Comment by rcorrie** [comment]
I get this too

![image](https://user-images.githubusercontent.com/6488063/31248191-fefd8b5e-a9e0-11e7-8bc4-536fe5486c56.png)

**Comment by rommyarb** [comment]
I found the solution:

Add **prop-types** to dependency
`npm i --save prop-types`

and revert back to version **0.4.1**
`npm i --save react-native-shimmer@0.4.1`

Now it works.

**Comment by oblador** [comment]
Unable to reproduce, it's possible your JS code is out of sync with your compiled binary. Closing for now, reopen with a reproduction if it still persists.
